CREATE TABLE RODOR_NAVS(
id NUMBER(5) NOT NULL,
app VARCHAR2(20) NOT NULL ,
parentcode VARCHAR2(20) NULL ,
code VARCHAR2(20) NOT NULL ,
uri VARCHAR2(256)  NULL ,
startdate TIMESTAMP NOT NULL ,
enddate TIMESTAMP NOT NULL ,
CONSTRAINT RODOR_DOMAINS_PK PRIMARY KEY(ID)
) 
LOGGING;
